---

- name: add the key for the Debian package repository of Jenkins
  shell: >
    wget -q -O - {{ jenkins.dl_url }} | apt-key add -
 
- name: add the following entry
  lineinfile: >
    dest=/etc/apt/sources.list
    line='deb http://pkg.jenkins-ci.org/debian binary/'

- name: install jenkins
  apt: pkg=jenkins update_cache=yes state=latest
