---

- name: add node.js ppa
  shell: curl -sL https://deb.nodesource.com/setup | bash -

- name: install nodejs
  apt: pkg="{{ item }}" update_cache=yes state=latest 
  with_items:
  - nodejs
  - build-essential 
  - npm

- name: npm package install
  npm: name=n global=yes state=latest

- name: n command
  command: n stable

- name: create symlink
  file: >
    state=link
    force=yes
    src='/usr/local/bin/node'
    path='/usr/bin/node'
    
    
