---

- name: install open JDK
  apt: pkg=python-pycurl update_cache=yes

- name: Add the webupd8 APT repository
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" state=present
  tags: jave

- name: Automatically accept the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  tags: java

- name: Install Oracle Java 7 SE SDK
  apt: pkg=oracle-jdk7-installer update-cache=yes state=latest force=yes
  tags: java
