Vagrant.configure(2) do |config|
  # config.vm.box = "bento/ubuntu-15.04"
  # config.vbguest.auto_update = false

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define :svr01 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.39", auto_config: false
    ### vbox name
    server.vm.hostname = 'svr01'
    ### box setting
    server.vm.box = "bento/ubuntu-16.04"
    ### bug fix
    server.vm.provision 'shell', inline: "ifconfig enp0s8 192.168.33.39" 
    server.vm.provision 'shell', inline: "sed -i 's/exit\ 0/ifconfig\ enp0s8\ 192\.168\.33\.39/g' /etc/rc.local" 
    server.vm.provision 'shell', inline: "echo 'exit 0' >> /etc/rc.local" 
    server.vm.provision 'shell', inline: "chmod 644 /home/vagrant/.ssh/authorized_keys" 
 end

  config.vm.provider "virtualbox" do |vb|
    ### vagrant hostname 
    vb.name = "try-nodejs"
    vb.customize ['modifyvm', :id,"--memory", 512]
    vb.customize ['modifyvm', :id,"--natdnshostresolver1", "on"]
    vb.customize ['modifyvm', :id,"--natdnsproxy1", "on"]
  end  
 
  ### settitng of synced_folder
  config.vm.synced_folder "../../", "/srv/try-nodejs", \
    :create => true, \
    :owner  => 'vagrant', \
    :group  => 'vagrant', \
    :mount_options => ['dmode=755,fmode=755'] 

  config.vm.provision :shell, :path => "ssh/init.sh"
 
end
